#!/bin/bash
set -e

# === CONFIGURATION SCRIPT FOR R PROJECT ENVIRONMENT ===
# Best Practice: Generates a project-level .Renviron file dynamically
# based on the currently active Conda/Micromamba environment.

# 1. Check if a Conda environment is currently active
if [ -z "$CONDA_PREFIX" ]; then
    echo "❌ Error: No Conda environment active."
    echo "👉 Please activate your environment first:"
    echo "   micromamba activate facs-comp-analysis"
    exit 1
fi

# 2. Define the target file (Project-level .Renviron)
# We use $(pwd) to ensure it's created in the current project root
PROJECT_RENVIRON="$(pwd)/.Renviron"

echo "🔧 Configuring R environment for: $CONDA_PREFIX"

# 3. Backup existing project-level .Renviron if it exists
if [ -f "$PROJECT_RENVIRON" ]; then
    echo "⚠️  Existing .Renviron found. Backing up to .Renviron.bak"
    cp "$PROJECT_RENVIRON" "${PROJECT_RENVIRON}.bak"
fi

# 4. Generate the .Renviron file
# We use dynamic paths from $CONDA_PREFIX instead of hardcoded /home/user/...
cat <<EOF > "$PROJECT_RENVIRON"
# --- Auto-generated by setup/setup_renviron.sh ---
# Environment: $(basename "$CONDA_PREFIX")
# Date: $(date)

# PATH: Prioritize environment binaries
PATH="${CONDA_PREFIX}/bin:\${PATH}"

# LIBRERIE: Fix CXXABI and compiler linking
LD_LIBRARY_PATH="${CONDA_PREFIX}/lib:\${LD_LIBRARY_PATH}"

# R LIBS: Location of environment-specific R packages
R_LIBS_USER="${CONDA_PREFIX}/lib/R/library"

# R HOME: R executable location
R_HOME="${CONDA_PREFIX}/lib/R"
EOF

echo "✓ Project-level .Renviron created at: $PROJECT_RENVIRON"
echo "🚀 Ready! Restart your R session for changes to take effect."
